server:
  port: 7090

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://localhost:7091
              predicates:
                - Path=/users/**

            - id: reserva-service
              uri: http://localhost:7092
              predicates:
                - Path=/reservas/**
            
            - id: producto-service
              uri: http://localhost:7093
              predicates:
                - Path=/productos/**
                
            - id: pago-service
              uri: http://localhost:7094
              predicates:
                - Path=/pagos/**

            - id: resena-service
              uri: http://localhost:7095
              predicates:
                - Path=/resenas/**
                
            - id: auth-service  
              uri: http://localhost:7096
              predicates:
                - Path=/auth/**
            - id: empleado-service
              uri: http://localhost:7097
              predicates:
                - Path=/empleados/**
                
            - id: inventario-service
              uri: http://localhost:7098
              predicates:
                - Path=/inventarios/**
            - id: notificacion-service
              uri: http://localhost:7099
              predicates:
                - Path=/notificaciones/**    

            - id: servicio-service
              uri: http://localhost:7100
              predicates:
                - Path=/servicios/**

            - id: sucursal-service
              uri: http://localhost:7101
              predicates:
                - Path=/sucursales/**

jwt:
  secret: barbershop-secret-key-2025-fullstack-duoc-uc-muy-segura