server:
  port: 7090

spring:
  main:
    web-application-type: reactive

  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: user-service
              uri: http://user-service:7091
              predicates:
                - Path=/users/**

            - id: reserva-service
              uri: http://reserva-service:7092
              predicates:
                - Path=/reservas/**

            - id: producto-service
              uri: http://producto-service:7093
              predicates:
                - Path=/productos/**

            - id: pago-service
              uri: http://pago-service:7094
              predicates:
                - Path=/pagos/**

            - id: resena-service
              uri: http://resena-service:7095
              predicates:
                - Path=/resenas/**

            - id: auth-service
              uri: http://auth-service:7096
              predicates:
                - Path=/auth/**

            - id: empleado-service
              uri: http://empleado-service:7097
              predicates:
                - Path=/empleados/**

            - id: inventario-service
              uri: http://inventario-service:7098
              predicates:
                - Path=/inventarios/**

            - id: notificacion-service
              uri: http://notificacion-service:7099
              predicates:
                - Path=/notificaciones/**

            - id: servicio-service
              uri: http://servicio-service:7100
              predicates:
                - Path=/servicios/**

            - id: sucursal-service
              uri: http://sucursal-service:7101
              predicates:
                - Path=/sucursales/**

jwt:
  secret: barbershop-secret-key-2025-fullstack-duoc-uc-muy-segura

springdoc:
  swagger-ui:
    path: /swagger-ui.html