server:
  port: 7091

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/db_barbershop_users?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.sql

springdoc:
  swagger-ui:
    path: /swagger-ui.html