server:
  port: 7095

spring:
  application:
    name: resena-service
  datasource:
    url: jdbc:mysql://localhost:3306/db_barbershop_resenas?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.sql

  springdoc:
    swagger-ui:
    path: /swagger-ui.html

# Ruta para consultar al user-service a través del Gateway
api:
  base-url: http://localhost:7090
  user: /users/%s/exists